# Generated by Django 4.2.4 on 2023-08-27 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_customer_account_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='+98', max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
