# Generated by Django 4.2.4 on 2023-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transaction_customer_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
